baseurl = "https://www.digitalinklingsblog.com"
title = "Digital Inklings"
author = "Owen Auch"
paginate = 3
theme = "tale"
sectionPagesMenu = "main"
description = "Digital Inklings: A blog at the intersection of technology and faith."
images = ["cloud-lake.JPG"]

[Author]
    name = "Owen Auch"
